services:
  endpoint-auditor:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${PROJECTS_ROOT_PATH}:/app/projects
    container_name: deprecate-endpoint-auditor
    environment:
      - PYTHONPATH=/app/src:/app/src/endpoint_auditor
    command: ["tail", "-f", "/dev/null"]
