services:
  endpoint-auditor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    container_name: deprecate-endpoint-auditor
    environment:
      - PYTHONPATH=/app/src
    command: ["tail", "-f", "/dev/null"]
